service:
  name: sharedoc

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    FILES_BUCKET_NAME: ${self:custom.FilesBucket.name}
    FILES_TABLE_NAME: ${self:custom.FilesTable.name}
  iamRoleStatements:
    - ${file(iam/FilesBucketIAM.yml):FilesBucketIAM}
    - ${file(iam/FilesTableIAM.yml):FilesTableIAM}

resources:
  Resources:
    FilesTable: ${file(resources/FilesTable.yml):FilesTable}
    FilesBucket: ${file(resources/FilesBucket.yml):FilesBucket}
    FilesBucketPolicy: ${file(resources/FilesBucket.yml):FilesBucketPolicy}
    


functions:
  sendfile:
    handler: src/handlers/sendfile.handler
    events:
      - http:
          method: PATCH
          path: /sendfile/{filename}
          cors: true
          authorizer: ${self:custom.authorizer}
  allfiles:
    handler: src/handlers/allfiles.handler
    events:
      - http:
          method: GET
          path: /allfiles
          cors: true
          authorizer: ${self:custom.authorizer}
  getfile:
    handler: src/handlers/getfile.handler
    events:
      - http:
          method: GET
          path: /getfile/{id}
          cors: true
  updatefile:
    handler: src/handlers/updatefile.handler
    events:
      - http:
          method: PATCH
          path: /updatefile/{id}
          cors: true
          authorizer: ${self:custom.authorizer}

          

custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  FilesBucket:
    name: files-bucket-bvncmli-${self:provider.stage}
  FilesTable:
    name: !Ref FilesTable
    arn: !GetAtt FilesTable.Arn
  bundle:
    linting: false
